# Generated by Django 4.2.5 on 2023-12-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_addkh_phone"),
    ]

    operations = [
        migrations.RemoveField(model_name="adddv", name="date",),
        migrations.RemoveField(model_name="shipping", name="address",),
        migrations.AddField(
            model_name="addkh",
            name="Note",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="addkh",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
