# Generated by Django 4.2.5 on 2023-12-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_adddv_date_remove_shipping_address_addkh_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="addkh",
            name="date",
            field=models.DateField(max_length=200, null=True),
        ),
    ]
