# Generated by Django 4.2.5 on 2023-12-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_lalale_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="addkh", name="user",),
    ]
