# Generated by Django 4.2.5 on 2023-12-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_addkh_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="addkh", name="user",),
    ]
