# Generated by Django 4.2.5 on 2023-12-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_addkh_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addkh",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
