# Generated by Django 4.2.5 on 2023-12-05 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_addkh_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="addnv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=200, null=True)),
                (
                    "group",
                    models.BooleanField(blank=True, default="Thợ Chính", null=True),
                ),
                ("phone", models.CharField(max_length=200, null=True)),
                ("email", models.CharField(max_length=200, null=True)),
                ("Note", models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(model_name="oder", name="oder",),
        migrations.RemoveField(model_name="oder", name="product",),
        migrations.RemoveField(model_name="shipping", name="custom",),
        migrations.RemoveField(model_name="shipping", name="oder",),
        migrations.RenameField(
            model_name="adddv", old_name="transaction_id", new_name="intime",
        ),
        migrations.RemoveField(model_name="adddv", name="complete",),
        migrations.RemoveField(model_name="adddv", name="custom",),
        migrations.AddField(
            model_name="adddv",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="adddv",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="adddv",
            name="price",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="adddv",
            name="time",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(name="lalale",),
        migrations.DeleteModel(name="Oder",),
        migrations.DeleteModel(name="Shipping",),
        migrations.AddField(
            model_name="adddv",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.addnv",
            ),
        ),
    ]
