# Generated by Django 4.2.5 on 2023-12-05 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_addnv_remove_oder_oder_remove_oder_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="groupkh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=200, null=True)),
                ("info", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="groupnv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=200, null=True)),
                ("info", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="addkh",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.groupkh",
            ),
        ),
        migrations.AlterField(
            model_name="addnv",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.groupnv",
            ),
        ),
    ]
