# Generated by Django 4.2.5 on 2023-12-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_groupkh_groupnv_addkh_group_alter_addnv_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="adddv",
            name="quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
